### ISSUE TITLE
python3 parseBLE01ZM.py

### ISSUE THREAD

**Issue by romibe** [rubinho101/MMM-01ZM#4]
pi@raspberrypi:~/MagicMirror/modules/MMM-01ZM/mitemp $ python3 parseBLE01ZM.py 
Traceback (most recent call last):
  File "parseBLE01ZM.py", line 20, in <module>
    app = Sanic()
  File "/home/pi/.local/lib/python3.7/site-packages/sanic/app.py", line 177, in __init__
    super().__init__(name=name)
  File "/home/pi/.local/lib/python3.7/site-packages/sanic/base/root.py", line 32, in __init__
    f"{class_name} instance cannot be unnamed. "
sanic.exceptions.SanicException: Sanic instance cannot be unnamed. Please use Sanic(name='your_application_name') instead.

**Comment by abdelhadj** [comment]
Hello,
i have same issue :(
any idea how to solve?

Thanks

**Comment by shadzik** [comment]
Change line 20 to something like:

`app = Sanic(name='app')`
